org: blockpos
app: block
service: api

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: "20201221"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParametersByPath
            - ssm:GetParameter
            - ssm:GetParameters
          Resource: 
            - arn:aws:ssm:*:*:parameter/*

  environment:
    SECRET_PREFIX: "/BlockPoS"
    STAGE: ${sls:stage}
    tatum_api_key: ${param:tatum_api_key}
    debug: ${param:debug}
    sender_host: ${param:sender_host}
    sender_port: ${param:sender_port}
    sender_secure: ${param:sender_secure}
    sender_username: ${param:sender_username}
    sender_password: ${param:sender_password}
    sender_name: ${param:sender_name}
    sender_email: ${param:sender_email}
    mongodb_connection: ${param:mongodb_connection}
    platform_url: ${param:platform_url}
    secret: ${param:secret}

functions:
  api:
    timeout: 30
    handler: ./src/api.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline